Test The Model

In [2]:
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.inception_v3 import preprocess_input
import numpy as np


In [5]:
model = load_model('/content/drive/MyDrive/IBM/Project/Updated-Xception-diabetic-retinopathy.h5')

In [8]:
#load ramdom image from local system
img = image.load_img(r'/content/drive/MyDrive/IBM/Project/upload/PDR.jpg' , target_size=(299,299))

In [12]:
#convert img to array
arrayImg = image.img_to_array(img)

In [10]:
import matplotlib.pyplot as plt

In [13]:
arrayImg.shape

(299, 299, 3)

In [14]:
import numpy as np
arrayImg = np.expand_dims(x , axis=0)
img_data = preprocess_input(arrayImg)
img_data.shape

(1, 299, 299, 3)

In [15]:
model.predict(img_data)

1/1 [==============================] - 2s 2s/step


array([[1.40166845e-11, 8.72857253e-09, 1.59445044e-08, 3.99780248e-07,
        9.99999523e-01]], dtype=float32)

In [16]:
output = np.argmax(model.predict(img_data), axis=1)

1/1 [==============================] - 0s 385ms/step


In [17]:
output == 0 , output == 1 , output == 2 , output == 3, output == 4

(array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([ True]))

In [18]:
index = ['No Diabetic Retinopathy' , 'Mild DR' , 'Moderate DR' , 'Severe DR' , 'Proliferative DR']
result = str(index[output[0]])
result

'Proliferative DR'